#!/bin/bash

for filename in ./*.mkv; do
    ffmpeg -i $filename -c:v libx264 -crf 22 -preset veryfast -c:a libmp3lame -q:a 4 $filename.avi
done

for filename in ./*.mp4; do
    ffmpeg -i $filename -c:v libx264 -crf 22 -preset veryfast -c:a libmp3lame -q:a 4 $filename.avi
done

for file in *.mkv.avi; do
      mv "$file" "${file/.mkv.avi/.avi}"
done

for file in *.mp4.avi; do
      mv "$file" "${file/.mp4.avi/.avi}"
done

mkdir "converted"

for file in *.avi; do
      cp "$file" "./converted"
      rm $file
done

